### ISSUE TITLE
Bazel build fails due to dependency that is not visible

### ISSUE THREAD

**Issue by jiawen** [pybind/pybind11_protobuf#42]
proto_cast_util has a dependency on ["@com_google_protobuf//:python/google/protobuf/pyext/_message.so"](https://github.com/pybind/pybind11_protobuf/blob/23b01b590021980cf5f0f5fd1c8d11696c22099d/pybind11_protobuf/BUILD#L75). However, it is not visible.

Building with `--check_visibility=false` succeeds however.

**Comment by jiawen** [comment]
Should we be depending on [protobuf_python](https://github.com/protocolbuffers/protobuf/blob/b360b9e388351aaed97f2ead98dd951fb5f1951e/BUILD#L1037) instead?

Minor tangent: Getting pybind11_protobuf to build with Bazel at all required `bind`ing`//external:python_headers` to something (because proto_api depends on it, and protobuf's WORKSPACE is set up weirdly) - this was not obvious - perhaps put it in docs somewhere?

**Comment by laramiel** [comment]
See https://github.com/pybind/pybind11_protobuf/blob/main/external/com_google_protobuf_build.patch

Basically @com_google_protobuf:://BUILD has updated and the patch no longer applies cleanly.

**Comment by laramiel** [comment]
... And we may not be applying that in the WORKSPACE file. Will look at this.

**Comment by laramiel** [comment]
I have updated our dependencies; I am not sure that this will fix this. We may want to change the dependency to `:protobuf_python`. If this doesn't work, do you have a hermetic respository / repro script for this?

**Comment by laramiel** [comment]
Followup on this: I've removed the visibility patch entirely and will close this issue. Reopen if it is still a problem with the latest commit.
