### ISSUE TITLE
Conversion not working for C++ api_implementation

### ISSUE THREAD

**Issue by srmainwaring** [pybind/pybind11_protobuf#44]
I have a simple example that works perfectly when `protoc` generates native Python for protobufs but is not working correctly when using the C++ implementation (i.e. cleaning, setting `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp`, then rebuilding)

The full example is here https://github.com/srmainwaring/pybind11_protobuf/tree/feature/extras.

System: macOS Big Sur 11.6.1
Python: 3.9.9 installed with brew
protoc: 3.19.1 installed with brew

The relevant portion of the stack trace is:

```bash
    msg = m.set_vector3d(msg)
TypeError: set_vector3d(): incompatible function arguments. The following argument types are supported:
    1. (msg: extras::msgs::Vector3d) -> None

Invoked with: x: 1.0
y: 2.0
z: 3.0
```

where the example is a variation of the basic example from the README comprising a pair of set and get functions returning and accepting a simple message.

The `isinstance` behaviour of returned types is also not working as expected.

Uninstalling the brew version of protobuf does not change the outcome. I expect this may be a user / configuration issue but can't spot where I'm going wrong. Any help appreciated.

**Comment by laramiel** [comment]
I think that at a high level I know what's happening: The c++ extension and the python fast_cpp_protos implementation refer to different descriptor pools.

I'm not sure what will have to happen to resolve this; it likely has to do with how extensions are built (re public symbols) and how pb2_py libraries are built, etc.

It may be possible to work around this by somehow linking against the specific python proto (`//extras/msgs:vector3d_py_pb2`) in the pybind_extension, but I'm not entirely sure about that:

**Comment by laramiel** [comment]
Ok, the root cause appears to be different descriptor pools because each `py_extension` may have a separate instance of protobuf implementation shared object.

**Comment by srmainwaring** [comment]
> The resulting commands.txt file does not include a c++ module file for vector_pb2_py. I think that you need to add something like `--define use_fast_cpp_protos=true` to a .bazelrc or invocation file, though I am not sure of the specifics of that in the open-source world.

Using a combination of PR #45 and `--define use_fast_cpp_protos=true` when building fixes the issue. 

Thank you for the quick fix and explanation, I was not aware of the additional flags needed when using `py_proto_library` with the C++ implementation.

**Comment by laramiel** [comment]
I think that `isinstance` will still be broken for this case, but ok.

**Comment by srmainwaring** [comment]
Yes - I was a bit quick off the mark there and ran the changes on a different example that didn't include all the cases from the original: as you note `isinstance` is not working.

**Comment by srmainwaring** [comment]
I've rebased my example to include #45 and added `isinstance` checks.

The example https://github.com/srmainwaring/pybind11_protobuf/blob/feature/extras/extras/python/extras_example.py contains additional cases highlighting the remaining issues.

### working

1. passing native python protobuf to extension expecting cpp protobuf
2. passing cpp wrapped  protobuf to extension expecting cpp protobuf
3. native Python protobuf accepts native Python protobuf in CopyFrom
4. cpp wrapped protobuf accepts cpp wrapped protobuf in CopyFrom

### not working

1. native Python protobuf accepts cpp wrapped protobuf in CopyFrom
2. cpp wrapped protobuf accepts native Python protobuf in CopyFrom

**Comment by davidtwomey** [comment]
Just adding that I am having similar difficulties with `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp`
as per: https://github.com/davidtwomey/pybind11-protobuf-bazel-example#notes

My goal was to be able to use a compiled pybind11 extension **outside of bazel** (for example within a jupyter notebook). 
This currently only seems possible with the python protobuf implementation i.e. explicitly setting `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`. 

(Have tried adding `--define use_fast_cpp_protos=true` when building)

**Comment by laramiel** [comment]
@srmainwaring I think that the remaining issues are due to the diamond .so problem, as described in the diff for commit #45 ; there are now two different Message*, and so CopyFrom may not see the incoming object as a protocol buffer.

Basically you want to link all c++ protos and the c++ python implementation together a single time.

How you might go about it:

Make a single .so that includes all the extensions.
Make a dummy .so that references that so & exports the symbols.

**Comment by laramiel** [comment]
Followup on this.

Basically there's no safe way to enable passing native protos between C++ extensions and python even using fast_cpp_proto option unless the build is hermetic; that is, all the proto-using extensions, including python protobufs, are built using the same config settings.

So I've disabled it in the latest cl, and we fallback to the python implementation.
Which means that this should work but incur copies at the boundaries.

**Comment by srmainwaring** [comment]
@laramiel ok that's clear - thanks for your time on this. It might be worth documenting the behaviour in the readme. On macOS for example if you install protobuf with brew (either directly or indirectly as a dependency), you get the c++ implementation by default and so users will need to actively disable this when building projects using `pybind11_protobuf`.

**Comment by laramiel** [comment]
Actually they won't need to disable it at all.

We just won't pass C++ protos across the boundary; we'll now serialize the proto using whatever python implementation is loaded and deserialize into a C++ proto.

It should work in whatever mode python is running.

**Comment by blais** [comment]
I haven't  followed all the details of this thread but read some of Laramie's comments and wanted to add that the ability to pass C++ protos across the language boundary is crucial in some context. I have a context where I will have a hermetic build and specifically want to avoid copies/serialization/deserialization using the proto API.
