### ISSUE TITLE
Compiler error when integrating with `pybind11 v2.4.3` project

### ISSUE THREAD

**Issue by nickguo** [pybind/pybind11_protobuf#74]
Hello, I am trying to integrate the latest `pybind11_protobuf` (commit `a3d93a93387af7fa57d72d56cfc0a4ba7f4a60e4`) into my project which uses `pybind 2.4.3` and `bazel`.

I am running into a compiler error on what seems to be an incompatibility between `pybind11` and `pybind11_protobuf`.  Do you have any advice for how to resolve this?
```
In file included from external/com_github_pybind_pybind11_protobuf/pybind11_protobuf/native_proto_caster.cc:1:
external/com_github_pybind_pybind11_protobuf/pybind11_protobuf/native_proto_caster.h:102:8: error: too many template arguments for class template 'move_only_holder_caster'
struct move_only_holder_caster<
       ^
external/pybind11/include/pybind11/cast.h:1518:8: note: template is declared here
struct move_only_holder_caster {
       ^
In file included from external/com_github_pybind_pybind11_protobuf/pybind11_protobuf/native_proto_caster.cc:1:
external/com_github_pybind_pybind11_protobuf/pybind11_protobuf/native_proto_caster.h:154:8: error: too many template arguments for class template 'copyable_holder_caster'
struct copyable_holder_caster<
       ^
external/pybind11/include/pybind11/cast.h:1438:8: note: template is declared here
struct copyable_holder_caster : public type_caster_base<type> {
       ^
2 errors generated.
```

Here is my bazel rule for `pybind11_protobuf`:
```
cc_library(
    name = "pybind11_protobuf",
    hdrs = glob([
        "pybind11_protobuf/*.h",
    ]),
    deps = [
        "@pybind11//:pybind11",
        "@com_google_protobuf//:protobuf",
        "@com_google_protobuf//:proto_api",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/types:optional"
    ],
    visibility = ["//visibility:public"],
    copts=[
        "-Iexternal/pybind11/include/include",
        "-Iexternal/pybind11/include",
        "-Iexternal/com_google_protobuf/include",
        "-Iexternal/com_google_absl/include"
    ]
)
```

**Comment by rwgk** [comment]
v2.4.3 is really old.

You need a pybind11 version that includes an added SFINAE tag:

https://github.com/pybind/pybind11/pull/2833

I recommend using the latest release (v2.9.1), although maybe v2.6 or v2.7 have that SFINAE tag already, I don't know off the top of my head.

**Comment by nickguo** [comment]
Thank you @rwgk !!  I really appreciate your fast reply.  Yes that makes sense. 😂 

Happy to report that after upgrading to latest pybind, `pybind11_protobuf` is working great in my project!!! 

This is going to save me a lot of boilerplate serialization & code.  Thank you again. 🙏  Please mark this thread as resolved

**Comment by rwgk** [comment]
Thanks for the feedback!
